const S4 = {
  masterComponents: ["S4"],
  components: [
    {
      id: "S4",
      label: "Seat Switch",
      category: "Switch",
      shape: "rectangle",
      connectors: [
        {
          id: "XS4",
          label: "XS4",
        },
      ],
      // Wire popup details for XS4 wire 500C (cavity 2 to XSP_500)
      wireDetails500C: {
        circuitNumber: "500C",
        wireSize: 0.8,
        wireColor: "YE",
        wireLength: 2377,
        wireType: "Regular",
        twistId: "",
        shieldId: "",
        wireOption: "",
        mark: "",
        from: {
          connectorNumber: "XS4",
          devName: "Seat switch",
          connPartNumber: "57M7535",
          termPartNo: "57M7546",
          sealPartNo: "",
          cavity: "2",
        },
        to: {
          connectorNumber: "XSP_500",
          devName: "Splice",
          connPartNumber: "",
          termPartNo: "",
          sealPartNo: "",
          cavity: "L",
        },
      },
      // Wire popup details for XS4 wire 800A (cavity 4 from XJ2)
      wireDetails800A: {
        circuitNumber: "800A",
        wireSize: 0.8,
        wireColor: "PK",
        wireLength: 2510,
        wireType: "Regular",
        twistId: "",
        shieldId: "",
        wireOption: "",
        mark: "",
        from: {
          connectorNumber: "XJ2",
          devName: "Instrument Cluster Controller",
          connPartNumber: "57M12920",
          termPartNo: "57M11448",
          sealPartNo: "",
          cavity: "3",
        },
        to: {
          connectorNumber: "XS4",
          devName: "Seat switch",
          connPartNumber: "57M7535",
          termPartNo: "57M7546",
          sealPartNo: "",
          cavity: "4",
        },
      },
    },
    {
      id: "SPL1",
      label: "Splice",
      category: "Splice",
      shape: "circle",
      connectors: [
        {
          id: "XSP_500",
          label: "XSP_500",
        },
      ],
      // Wire details for XSP_500 if needed
      wireDetails500C: {
        circuitNumber: "500C",
        wireSize: 0.8,
        wireColor: "YE",
        wireLength: 2377,
        wireType: "Regular",
        twistId: "",
        shieldId: "",
        wireOption: "",
        mark: "",
        from: {
          connectorNumber: "XS4",
          devName: "Seat switch",
          connPartNumber: "57M7535",
          termPartNo: "57M7546",
          sealPartNo: "",
          cavity: "2",
        },
        to: {
          connectorNumber: "XSP_500",
          devName: "Splice",
          connPartNumber: "",
          termPartNo: "",
          sealPartNo: "",
          cavity: "L",
        },
      },
    },
    {
      id: "ICC",
      label: "Instrument Cluster Controller",
      category: "Transistor",
      shape: "rectangle",
      connectors: [
        {
          id: "XJ2",
          label: "XJ2",
        },
      ],
      // Wire details for XJ2 wire 800A (to XS4)
      wireDetails800A: {
        circuitNumber: "800A",
        wireSize: 0.8,
        wireColor: "PK",
        wireLength: 2510,
        wireType: "Regular",
        twistId: "",
        shieldId: "",
        wireOption: "",
        mark: "",
        from: {
          connectorNumber: "XJ2",
          devName: "Instrument Cluster Controller",
          connPartNumber: "57M12920",
          termPartNo: "57M11448",
          sealPartNo: "",
          cavity: "3",
        },
        to: {
          connectorNumber: "XS4",
          devName: "Seat switch",
          connPartNumber: "57M7535",
          termPartNo: "57M7546",
          sealPartNo: "",
          cavity: "4",
        },
      },
    },
  ],
  connections: [
    {
      color: "yellow",
      from: {
        componentId: "S4",
        connectorId: "XS4",
        cavity: "2",
      },
      to: {
        componentId: "SPL1",
        connectorId: "XSP_500",
        cavity: "L",
      },
      label: "",
      wireDetails: {
        circuitNumber: "500C",
        wireSize: 0.8,
        wireColor: "YE",
        wireLength: 2377,
        wireType: "Regular",
        twistId: "",
        shieldId: "",
        wireOption: "",
        mark: "",
        from: {
          connectorNumber: "XS4",
          devName: "Seat switch",
          connPartNumber: "57M7535",
          termPartNo: "57M7546",
          sealPartNo: "",
          cavity: "2",
        },
        to: {
          connectorNumber: "XSP_500",
          devName: "Splice",
          connPartNumber: "",
          termPartNo: "",
          sealPartNo: "",
          cavity: "L",
        },
      },
    },
    {
      color: "pink",
      from: {
        componentId: "ICC",
        connectorId: "XJ2",
        cavity: "3",
      },
      to: {
        componentId: "S4",
        connectorId: "XS4",
        cavity: "4",
      },
      label: "",
      wireDetails: {
        circuitNumber: "800A",
        wireSize: 0.8,
        wireColor: "PK",
        wireLength: 2510,
        wireType: "Regular",
        twistId: "",
        shieldId: "",
        wireOption: "",
        mark: "",
        from: {
          connectorNumber: "XJ2",
          devName: "Instrument Cluster Controller",
          connPartNumber: "57M12920",
          termPartNo: "57M11448",
          sealPartNo: "",
          cavity: "3",
        },
        to: {
          connectorNumber: "XS4",
          devName: "Seat switch",
          connPartNumber: "57M7535",
          termPartNo: "57M7546",
          sealPartNo: "",
          cavity: "4",
        },
      },
    },
  ],
};
export default S4;
